services:
  crawler:
    build:
      context: .
      shm_size: 4gb
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - ./scripts:/scripts
    environment:
      VNC_PW: password
      START_INDEX: ${START_INDEX}
      END_INDEX: ${END_INDEX}
    container_name: crawler_${INDEX}
    networks:
      - shared_network
    ports:
      - "${VNC_PORT}:5901"
      - "${NOVNC_PORT}:6080"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    tty: true
    stdin_open: true
