services:
  xfce-vnc:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: ubuntu-xfce-vnc-container_name
    ports:
      - "5901:5901" # VNC port
      - "6080:6080" # novnc
    volumes:
      - ./app:/app
      - ./scripts/cloudflare_setup.sh:/cloudflare_setup.sh
      - ./scripts/startup.sh:/startup.sh
      - ./scripts/run.sh:/run.sh
    environment:
      VNC_PW: "password" # Set a password for VNC access
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    stdin_open: true
    tty: true
